### ISSUE TITLE
[swift] todolist / api tracking issue

### ISSUE THREAD

**Issue by ghost** [hiero-ledger/hiero-sdk-rust#268]
Checked directly against Java.

### API
- [x] #219
- [x] #220
- [x] #221
- [x] `AccountBalanceQuery` (todo: check if the way of doing getters in this project is okay)
- [x] #222
- [x] `AccountDeleteTransaction`
- [x] #223
- [x] #224
- [x] #384
- [x] `AccountInfoQuery`
- [x] `AccountRecordsQuery`
- [x] `AccountStakersQuery`
- [x] #225
- [x] `AddressBookQuery`
- [x] #316 
- [ ] #226
- [x] `ContractByteCodeQuery`
- [x] `ContractCallQuery`
- [x] #385
- [x] `ContractCreateTransaction`
- [x] #227
- [x] #228
- [x] #372
- [x] #229
- [x] #382
- [x] #230 
- [x] #231
- [x] #232
- [x] #369
- [x] #233
- [x] `CustomFee` (complete redesign to match Java is needed)
- [x] `CustomFeeBase` (see `CustomFee`)
- [x] `CustomFixedFee` (see `CustomFee`)
- [x] `CustomFractionalFee` (see `CustomFee`)
- [x] `CustomRoyaltyFee` (see `CustomFee`)
- [x] #368
- [x] #403
- [x] `EthereumTransaction`
- [x] #404
- [x] #405
- [x] #406
- [x] `EvmAddress`
- [x] #367
- [x] #450
- [x] ~`ExecutionState` (?)~
- [x] #451
- [x] #452
- [x] #402
- [x] #401
- [x] #400
- [x] #399
- [x] #234
- [x] #235
- [x] #236
- [x] `FileDeleteTransaction`
- [x] #237
- [x] #238
- [x] `FileInfoQuery`
- [x] #239
- [x] `FreezeTransaction`
- [x] `FreezeType`
- [x] #240
- [x] `HbarAllowance`
- [x] #241
- [x] #242
- [x] #364
- [x] #243
- [x] `Mnemonic`
- [x] #244
-  [x] `NetworkVersionInfoQuery`
- [x] #245
- [x] `NodeAddress`
- [x] #365
- [x] #246
- [x] #409
- [x] `ProxyStaker`
- [x] #247
- [x] Query
- [x] ~`RequestType`~
- [x] `ScheduleCreateTransaction`
- [x] `ScheduleDeleteTransaction`
- [x] #349
- [x] #248
- [x] #249
- [x] #250
- [x] #251
- [x] #252
- [x] `Status`
- [x] ~`SubscriptionHandle`?~
- [x] `SystemDeleteTransaction`
- [x] `SystemUndeleteTransaction`
- [x] `TokenAllowance`
- [x] `TokenAssociateTransaction`
- [x] #253
- [x] #254
- [x] #255
- [x] `TokenDeleteTransaction`
- [x] `TokenDisassociateTransaction`
- [x] `TokenFeeScheduleUpdateTransaction`
- [x] `TokenFreezeTransaction`
- [x] `TokenGrantKycTransaction`
- [x] #344
- [x] #345
- [x] #256
- [x] `TokenMintTransaction`
- [x] `TokenNftAllowance`
- [x] #348
- [x] #257
- [x] `TokenNftTransfer` (internal class)
- [x] `TokenPauseTransaction`
- [x] #398
- [x] `TokenRevokeKeyTransaction`
- [x] `TokenSupplyType`
- [x] `TokenTransfer` (internal class)
- [x] `TokenType`
- [x] `TokenUnfreezeTransaction`
- [x] `TokenUnpauseTransaction`
- [x] #258
- [x] #259
- [x] `TopicCreateTransaction`
- [x] `TopicDeleteTransaction`
- [x] #346
- [x] #347
- [x] `TopicInfoQuery`
- [x] #407
- [x] #408
- [x] `TopicMessageQuery`
- [x] #260
- [x] #261
- [x] #262
- [x] `TransactionFeeSchedule`
- [x] `TransactionId`
- [x] #263
- [x] #264
- [x] #265
- [x] #266
- [x] #267
- [x] `Transfer` (internal class)

### Examples

Tracking https://github.com/hashgraph/hedera-sdk-java/tree/main/examples/src/main/java
Tracking https://github.com/hashgraph/hedera-sdk-rust/tree/main/sdk/swift/Examples

- [x] #410
- [x] #411
- [x] #412
- [x] #413
- [x] #414
- [x] #415
- [x] `CreateAccount`
- [x] #416
- [x] #337
- [x] #417
- [x] #418
- [x] #338
- [x] #419
- [x] `DeleteAccount`
- [x] #420
- [x] #421
- [x] `GenerateKey`
- [x] #339
- [x] `GetAccountBalance`
- [x] `GetAccountInfo`
- [x] `GetAddressBook`
- [x] #422
- [x] `GetFileContents`
- [x] #423
- [x] #424
- [x] #425
- [x] #426
- [x] #427
- [x] #428
- [x] #429
- [x] #430
- [x] #431
- [x] #432
- [x] #433
- [x] #434
- [x] #435
- [x] `TransferCrypto` (exists but is named `TransferHbar`)
- [x] #436
- [x] #437
- [x] #438

**Comment by izik1** [comment]
I think this can be closed now
